package DentalCare.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionListener;
import DentalCare.model.Appointment;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Martin
 */
public class CalendarDayView extends javax.swing.JPanel {

    /**
     * Creates new form calendarPanel
     */
    public CalendarDayView() {
        initComponents();;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendar2 = new javax.swing.JPanel();
        weekDayNamesPanel = new javax.swing.JPanel();
        dayLabel = new javax.swing.JLabel();
        weekElements2 = new javax.swing.JPanel();
        dayPanel = new javax.swing.JPanel();
        appointment = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        patientPanel = new javax.swing.JPanel();
        patient = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        previousWeek = new javax.swing.JButton();
        nextWeek = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        calendar2.setBackground(new java.awt.Color(255, 255, 255));
        calendar2.setToolTipText("");

        weekDayNamesPanel.setBackground(new java.awt.Color(255, 255, 255));

        dayLabel.setText("Monday");
        weekDayNamesPanel.add(dayLabel);

        weekElements2.setLayout(new java.awt.GridLayout(1, 7));

        dayPanel.setBackground(new java.awt.Color(255, 255, 255));
        dayPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        dayPanel.setMinimumSize(new java.awt.Dimension(210, 56));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
        flowLayout2.setAlignOnBaseline(true);
        dayPanel.setLayout(flowLayout2);

        appointment.setBackground(new java.awt.Color(237, 250, 250));
        appointment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        appointment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appointment.setEnabled(false);
        appointment.setPreferredSize(new java.awt.Dimension(600, 100));
        appointment.setLayout(new java.awt.BorderLayout());

        time.setText("15:00 - 15:50");
        time.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 7, 1, 1));
        appointment.add(time, java.awt.BorderLayout.PAGE_START);

        patientPanel.setBackground(new java.awt.Color(237, 250, 250));
        patientPanel.setLayout(new java.awt.BorderLayout());

        patient.setText("James Doe");
        patient.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 7, 1, 1));
        patientPanel.add(patient, java.awt.BorderLayout.PAGE_START);

        appointment.add(patientPanel, java.awt.BorderLayout.CENTER);

        dayPanel.add(appointment);

        weekElements2.add(dayPanel);

        javax.swing.GroupLayout calendar2Layout = new javax.swing.GroupLayout(calendar2);
        calendar2.setLayout(calendar2Layout);
        calendar2Layout.setHorizontalGroup(
            calendar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(weekDayNamesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(weekElements2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        calendar2Layout.setVerticalGroup(
            calendar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendar2Layout.createSequentialGroup()
                .addComponent(weekDayNamesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekElements2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );

        add(calendar2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        previousWeek.setText("Previous Day");
        previousWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousWeekActionPerformed(evt);
            }
        });
        jPanel1.add(previousWeek);

        nextWeek.setText("Next Day");
        jPanel1.add(nextWeek);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void previousWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousWeekActionPerformed

    public void addAppointmentArray(Appointment[] appointments) {
        
        clearAll();
        
        for(Appointment app : appointments) {
            javax.swing.JPanel appointment = new javax.swing.JPanel();
            javax.swing.JLabel time =  new javax.swing.JLabel();
            javax.swing.JLabel patient = new javax.swing.JLabel();
            javax.swing.JPanel patientPanel = new javax.swing.JPanel();

            appointment.setBackground(new java.awt.Color(237, 250, 250));
            appointment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            appointment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            appointment.setEnabled(false);
            appointment.setPreferredSize(new java.awt.Dimension(600, 100));
            appointment.setLayout(new java.awt.BorderLayout());

            DateTimeFormatter formatterTime = DateTimeFormatter.ofPattern("HH:mm");
            String startTime = app.getStartTime().format(formatterTime);
            String endTime = app.getEndTime().format(formatterTime);
            
            time.setText(startTime+" - "+endTime);
            time.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 7, 1, 1));
            appointment.add(time, java.awt.BorderLayout.PAGE_START);

            patientPanel.setBackground(new java.awt.Color(237, 250, 250));
            patientPanel.setLayout(new java.awt.BorderLayout());

            patient.setText(app.getFullName());
            patient.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 7, 1, 1));
            patientPanel.add(patient, java.awt.BorderLayout.PAGE_START);

            appointment.add(patientPanel, java.awt.BorderLayout.CENTER);
            dayPanel.add(appointment);

            updateDayLabel(app.getDate().getDayOfWeek().getValue());
        }
        
            dayPanel.revalidate();
            dayPanel.repaint();
    }
    
    private void updateDayLabel(int day) {
        dayLabel.setText(dayOfWeekStrings[day]);
        weekDayNamesPanel.revalidate();
        weekDayNamesPanel.repaint();
    }
    public void addChangeDayListener(ActionListener previous, ActionListener next) {
        previousWeek.addActionListener(previous);
        nextWeek.addActionListener(next);
    }
   
    public void clearAll() {
        dayPanel.removeAll();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appointment;
    private javax.swing.JPanel calendar2;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JPanel dayPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextWeek;
    private javax.swing.JLabel patient;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JButton previousWeek;
    private javax.swing.JLabel time;
    private javax.swing.JPanel weekDayNamesPanel;
    private javax.swing.JPanel weekElements2;
    // End of variables declaration//GEN-END:variables
    
    private final String[] dayOfWeekStrings = {"","Monday","Tuesday","Wednesday","Thurday","Friday"};

}
