/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DentalCare;

import DentalCare.model.HealthCarePlan;
import DentalCare.model.Address;
import DentalCare.model.Patient;
import DentalCare.model.Treatment;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import DentalCare.model.Appointment;
import DentalCare.model.Partner;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class SecretaryController extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryController
     */
    public SecretaryController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        mainPanel = new javax.swing.JPanel();
        calendars = new javax.swing.JTabbedPane();
        dentistCalendar = new DentalCare.views.CalendarPanel();
        hygienistCalendar = new DentalCare.views.CalendarPanel();
        bookAppointmentPanel = new javax.swing.JPanel();
        bookAppointmentTitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookAppointmentLowerPanel = new javax.swing.JPanel();
        searchPanel = new DentalCare.views.SearchPatientPanel();
        bookAppointmentForm = new DentalCare.views.BookAppointmentPanel();
        newPatientPanel = new DentalCare.views.NewPatientPanel();
        cancelAppointmentPanel = new javax.swing.JPanel();
        cancelAppointmentTitlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        canceAppointmentLowerPanel = new javax.swing.JPanel();
        searchPanel1 = new DentalCare.views.SearchPatientPanel();
        cancelAppointmentForm = new DentalCare.views.cancelAppointmentPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        viewMenu = new javax.swing.JMenu();
        calendarMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        newPatientMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        bookAppointmentMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        calendars.addTab("Dentist", dentistCalendar);
        calendars.addTab("Hygienist", hygienistCalendar);

        mainPanel.add(calendars, "calendars");

        bookAppointmentPanel.setLayout(new java.awt.BorderLayout());

        bookAppointmentTitlePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Book an Appointment");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bookAppointmentTitlePanelLayout = new javax.swing.GroupLayout(bookAppointmentTitlePanel);
        bookAppointmentTitlePanel.setLayout(bookAppointmentTitlePanelLayout);
        bookAppointmentTitlePanelLayout.setHorizontalGroup(
            bookAppointmentTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookAppointmentTitlePanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(1743, Short.MAX_VALUE))
        );
        bookAppointmentTitlePanelLayout.setVerticalGroup(
            bookAppointmentTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookAppointmentTitlePanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        bookAppointmentPanel.add(bookAppointmentTitlePanel, java.awt.BorderLayout.PAGE_START);

        bookAppointmentLowerPanel.setLayout(new java.awt.BorderLayout());
        bookAppointmentLowerPanel.add(searchPanel, java.awt.BorderLayout.PAGE_START);
        bookAppointmentLowerPanel.add(bookAppointmentForm, java.awt.BorderLayout.CENTER);

        bookAppointmentPanel.add(bookAppointmentLowerPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(bookAppointmentPanel, "bookAppointment");
        mainPanel.add(newPatientPanel, "newPatient");

        cancelAppointmentPanel.setLayout(new java.awt.BorderLayout());

        cancelAppointmentTitlePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Cancel Appointment");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cancelAppointmentTitlePanelLayout = new javax.swing.GroupLayout(cancelAppointmentTitlePanel);
        cancelAppointmentTitlePanel.setLayout(cancelAppointmentTitlePanelLayout);
        cancelAppointmentTitlePanelLayout.setHorizontalGroup(
            cancelAppointmentTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelAppointmentTitlePanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel2)
                .addContainerGap(1767, Short.MAX_VALUE))
        );
        cancelAppointmentTitlePanelLayout.setVerticalGroup(
            cancelAppointmentTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelAppointmentTitlePanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );

        cancelAppointmentPanel.add(cancelAppointmentTitlePanel, java.awt.BorderLayout.PAGE_START);

        canceAppointmentLowerPanel.setLayout(new java.awt.BorderLayout());
        canceAppointmentLowerPanel.add(searchPanel1, java.awt.BorderLayout.PAGE_START);
        canceAppointmentLowerPanel.add(cancelAppointmentForm, java.awt.BorderLayout.CENTER);

        cancelAppointmentPanel.add(canceAppointmentLowerPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(cancelAppointmentPanel, "cancelAppointment");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        viewMenu.setText("View");
        viewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMenuActionPerformed(evt);
            }
        });

        calendarMenu.setText("Calendars");
        calendarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarMenuActionPerformed(evt);
            }
        });
        viewMenu.add(calendarMenu);

        jMenuBar1.add(viewMenu);
        viewMenu.getAccessibleContext().setAccessibleName("calendars");

        jMenu2.setText("Patients");

        newPatientMenu.setText("Register New Patient");
        newPatientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientMenuActionPerformed(evt);
            }
        });
        jMenu2.add(newPatientMenu);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Appointment");

        bookAppointmentMenu.setText("Book an appointment");
        bookAppointmentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentMenuActionPerformed(evt);
            }
        });
        jMenu1.add(bookAppointmentMenu);

        jMenuItem1.setText("Cancel Appointment");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMenuActionPerformed
        
    }//GEN-LAST:event_viewMenuActionPerformed
    

    // Menu items links in panel
    private void newPatientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientMenuActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "newPatient" );
        addNewPatientPanelListener();
    }//GEN-LAST:event_newPatientMenuActionPerformed

    private void calendarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarMenuActionPerformed
        // Get list of appointments for both Dentist and Hygienist
        //dentistCalendar.addAppointmentArray(dentistAppointments)
        //hygienistCalendar.addAppointmentArray(hygienistAppointments)
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11
        addDentistCalendarPanelListener();
        addHygienistCalendarPanelListener();
        LocalDateTime now = LocalDateTime.now();
        currentWeek = now.with(DayOfWeek.MONDAY);
    }//GEN-LAST:event_calendarMenuActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        addSearchPanelListener();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void bookAppointmentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentMenuActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "bookAppointment" );
        combine();
        addSearchPanelListener();
        addBookAppointmentPanelListener();
    }//GEN-LAST:event_bookAppointmentMenuActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.show(mainPanel, "cancelAppointment" );
        addCancelCalendarPanelListener();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    


    // Listeners for all panels
    
            private void addNewPatientPanelListener() {
                newPatientPanel.addSaveActionListener((ActionEvent e) -> {
                    try {
                        int houseNumber = newPatientPanel.getHouseNumber();
                        String street = newPatientPanel.getStreet();
                        String district = newPatientPanel.getDistrict();
                        String city = newPatientPanel.getCity();
                        String postCode = newPatientPanel.getPostCode();
                        Address address = new Address(houseNumber,street,district,city,postCode);

                        String title = newPatientPanel.getTitle();
                        String forename = newPatientPanel.getForename();
                        String surname = newPatientPanel.getSurname();
                        LocalDate dateOfBirth = newPatientPanel.getDateOfBirth();
                        int contactNumber = newPatientPanel.getContactNumber();

                        String healthPlanName = newPatientPanel.getHealthPlan();
                        HealthCarePlan healthPlan = new HealthCarePlan(healthPlanName);

                        Treatment[] treatments = null;
                        Appointment[] appointments = null;
                        

                        Patient patient = new Patient(title, forename, surname,dateOfBirth, contactNumber, healthPlan,treatments,appointments);
                        
                        //Add patient to database method here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                        
                        JOptionPane.showMessageDialog(null, "Data Submitted");
                        newPatientPanel.clearAll();
                    }catch(NumberFormatException el) {
                        JOptionPane.showMessageDialog(null, "Incorrect Input  - Try again","Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                   
                    

                });
            }
            
            private void addSearchPanelListener() {
                searchPanel.addSearchActionListener((ActionEvent e) -> {
                    try {
                        bookAppointmentForm.clearPatientName();
                        
                        LocalDate dateOfBirth = searchPanel.getDateOfBirth();
                        int houseNumber = searchPanel.getHouseNumber();
                        String postCode = searchPanel.getPostCode();
                        
                        /// Missing impliementation !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11
                        //Method here should turn an array of patient object
                        Patient[] patients = null;
                        bookAppointmentForm.updatePatientNames(patientExamples);
                        
                        
                    }catch(NumberFormatException el) {
                        JOptionPane.showMessageDialog(null, "Incorrect Input  - Try again","Error", JOptionPane.ERROR_MESSAGE);
                    }

                });
            }
            
            private void addBookAppointmentPanelListener() {
               bookAppointmentForm.addSaveActionListener((ActionEvent e) -> {
                    try {
                        
                        Patient patient = bookAppointmentForm.getPatientName();
                        String partner = bookAppointmentForm.getPartner().toUpperCase();
                        LocalDateTime startTime = bookAppointmentForm.getStartTime();
                        LocalDateTime endTime = bookAppointmentForm.getEndTime();
                        Treatment[] treatments = bookAppointmentForm.getTreatments();
                       
                        String fullName = patient.getForename() +" "+patient.getSurname();
                        Appointment appointment =  new Appointment(treatments,Partner.valueOf(partner),fullName,startTime,endTime);
                        
                        // Book appointment into Database !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                        
                        JOptionPane.showMessageDialog(null, "Appointment is booked");
                        
                        bookAppointmentForm.clearAll();
                    }catch(NumberFormatException | ArrayIndexOutOfBoundsException el) {
                        JOptionPane.showMessageDialog(null, "Incorrect Input  - Try again","Error", JOptionPane.ERROR_MESSAGE);
                    }
                    

                });
            }
            
            private void addDentistCalendarPanelListener() {
                
                dentistCalendar.addChangeWeekListener((ActionEvent e) -> {
                    // Get list of appointments for both Dentist and Hygienist
                    //dentistCalendar.addAppointmentArray(dentistAppointments)
                    currentWeek.minusDays(7);  
                }, (ActionEvent e) -> {
                    // Get list of appointments for Dentist with changed week
                    //dentistCalendar.addAppointmentArray(dentistAppointments)
                    currentWeek.plusDays(7);
                });
                 
            }
            
            private void addHygienistCalendarPanelListener() {
                
                hygienistCalendar.addChangeWeekListener((ActionEvent e) -> {
                    // Get list of appointments for both Dentist and Hygienist
                    //dentistCalendar.addAppointmentArray(dentistAppointments)
                    currentWeek.minusDays(7);  
                }, (ActionEvent e) -> {
                    // Get list of appointments for Dentist with changed week
                    //dentistCalendar.addAppointmentArray(dentistAppointments)
                    currentWeek.plusDays(7);
                });
                 
            }
            
            private void addCancelCalendarPanelListener() {
                
                cancelAppointmentForm.addCancelListener((ActionEvent e) -> {
                    Appointment appointment = cancelAppointmentForm.getAppointmentComboBox();
                    
                    //Methods here to canel the appointment from the database
                    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
                });
                 
            }
            
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryController().setVisible(true);
            }
        });
    }
    private Patient[] patientExamples = new Patient[2];
    private Patient patient1 = examplePatient("max");
    private Patient patient2 = examplePatient("Martin");
    
    
    public void combine() {
        patientExamples[0] = patient1;
        patientExamples[1] = patient2;
    }
   
    
    public Patient examplePatient(String name) {
            int houseNumber = 45;
            String street = "bowen street";
            String district = "East side";
            String city = "Crewe";
            String postCode = "CW2 564";
            Address address = new Address(houseNumber,street,district,city,postCode);
            
            String title = "Mr";
            String forename = name;
            String surname = "taylor";
            LocalDate dateOfBirth = LocalDate.now();
            int contactNumber = 565657565;
            
            String healthPlanName = "NHS";
            HealthCarePlan healthPlan = new HealthCarePlan(healthPlanName);
            
            Treatment[] treatments = null;
            Appointment[] appointments = null;
            
            Patient patient = new Patient(title, forename, surname,dateOfBirth, contactNumber, healthPlan,treatments, appointments);
            
            return patient;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DentalCare.views.BookAppointmentPanel bookAppointmentForm;
    private javax.swing.JPanel bookAppointmentLowerPanel;
    private javax.swing.JMenuItem bookAppointmentMenu;
    private javax.swing.JPanel bookAppointmentPanel;
    private javax.swing.JPanel bookAppointmentTitlePanel;
    private javax.swing.JMenuItem calendarMenu;
    private javax.swing.JTabbedPane calendars;
    private javax.swing.JPanel canceAppointmentLowerPanel;
    private DentalCare.views.cancelAppointmentPanel cancelAppointmentForm;
    private javax.swing.JPanel cancelAppointmentPanel;
    private javax.swing.JPanel cancelAppointmentTitlePanel;
    private DentalCare.views.CalendarPanel dentistCalendar;
    private DentalCare.views.CalendarPanel hygienistCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem newPatientMenu;
    private DentalCare.views.NewPatientPanel newPatientPanel;
    private DentalCare.views.SearchPatientPanel searchPanel;
    private DentalCare.views.SearchPatientPanel searchPanel1;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables

   //More variables. 
   private LocalDateTime currentWeek;
}
